# Libraries

In [16]:
import pandas as pd
import numpy as np
from matplotlib import pyplot
from keras import layers
from keras.models import Model
import os

# Dense Model

In [17]:
def DenseModel(dim_1, dim_2):
    inputs = layers.Input(shape = (dim_1, dim_2))
    
    outputs = layers.Dense(10, activation='softmax')(inputs)
    
    model = Model(inputs=inputs, outputs=outputs)
    return model

In [18]:
DenseModel(28, 28).summary()

Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_5 (InputLayer)        [(None, 28, 28)]          0

 dense_4 (Dense)             (None, 28, 10)            290

=================================================================
Total params: 290
Trainable params: 290
Non-trainable params: 0
_________________________________________________________________

In [19]:
pd.read_csv("./dataset/fashion-mnist_train.csv")

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59996,1,0,0,0,0,0,0,0,0,0,...,73,0,0,0,0,0,0,0,0,0
59997,8,0,0,0,0,0,0,0,0,0,...,160,162,163,135,94,0,0,0,0,0
59998,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59999,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
os.path.exists("./dataset/fashion-mnist_train.csv")

True

In [23]:
path = os.path.join("dataset", "fashion-mnist_train.csv")
os.path.exists(path)

True